### ISSUE TITLE
Remove block system; create a static homepage with banner

### ISSUE THREAD

**Issue by carlvitzthum** [hms-dbmi/fourfront#120]
Banner should include a welcome message with number of experiments, biosources, assays, etc.
Make news populate from a JSON (maybe start with static at first)

**Comment by burakalver** [comment]
"welcome to 4DN data portal. We host 0 4DN experiments from 0 different cell types, and 201 external experiments from 7 different cell types." Needs #132

**Comment by carlvitzthum** [comment]
Finished homepage and added static routing; made a banner that presents 4DN and external experiment numbers & biosources number.
