### ISSUE TITLE
Navbar enhancements

### ISSUE THREAD

**Issue by carlvitzthum** [hms-dbmi/fourfront#121]
Add an account icon (maybe a custom SVG?)

Change brand so that it includes "Data Portal". Create multiple drafts and present to group

**Comment by ngehlenborg** [comment]
We should pick (and purchase) and icon set to use on the site, e.g. from https://symbolset.com/icons.

**Comment by carlvitzthum** [comment]
My suggestion: https://symbolset.com/icons/black-tie-solid

**Comment by ngehlenborg** [comment]
I am wondering if https://symbolset.com/icons/black-tie-regular is a better match for the Work Sans font. One downside of the Black Tie icons set is the weird user symbol. Gizmo (https://symbolset.com/icons/gizmo) has a bunch of better user icons.

**Comment by carlvitzthum** [comment]
Once icon set is decided upon, will update announcements to use collapsible content icons.

**Comment by carlvitzthum** [comment]
This is essentially finished, just needs to add the new icon when we buy the set. Closing.
