### ISSUE TITLE
add external vs. 4DN classification to metadata

### ISSUE THREAD

**Issue by burakalver** [hms-dbmi/fourfront#132]
We need to distinguish between 4DN-funded vs other experiments. (We might need a policy on which non-4DN experiments will be in our system, but let's ignore that for now.)

We may also need a similar classification for biosources, biosamples etc.

At least 3 cases where this distinction will appear:
- Similar to ENCODE's "encode2" "encode3" "roadmap" logos on the experiment page, we need to indicate the source of an experiment's funding.
- facets
- on the home page, we probably want "welcome to 4DN data portal. We host 0 4DN experiments from 0 different cell types, and 201 external experiments from 7 different cell types." where cell types = biosources.

This ticket can be closed once we know the metadata schemas are clear on the matter.

**Comment by aschroed** [comment]
I'm going to close this and create a new ticket for Carl so he is aware we added 'project' to award and this is what he should use for attribution to 4DN or External on web pages.
