### ISSUE TITLE
Submitting items with attachments

### ISSUE THREAD

**Issue by KorayKirli** [hms-dbmi/fourfront#135]
It is not clear to me what to put in the field "Attachment:object". Although we have the attachment as an object in the mixins, it is not a collection with items that can be referenced. Can we modify the system such that one can put the file path in the attachments and this file gets uploaded. We have a simple select and upload interface in the user interface, there should be a simple rest api version of this action I guess.

**Comment by j1z0** [comment]
@Koray that is how the import_data.py script works, according to the docs the field name should be 'attachment:object' and not "Attachment:object".  So change to that and it will try to read the file and upload it from the specified path.
