### ISSUE TITLE
Use award.project as mechanism for showing '4DN' or 'External' as data provider.

### ISSUE THREAD

**Issue by aschroed** [hms-dbmi/fourfront#140]
On the encode site they appear to use a combination of award.project and award.rfa (or maybe only one or the other) to display the little images in experiment that show a data attribution eg. Encode : Encode phase 3 icons in the attribution field of https://www.encodeproject.org/experiments/ENCSR209YCR/

We want to base this attribution simply on the project field in the award schema.

**Comment by carlvitzthum** [comment]
Done in the banner; will be implemented in experiment view when that is made.
