### ISSUE TITLE
Redesign of facet browser 

### ISSUE THREAD

**Issue by ngehlenborg** [hms-dbmi/fourfront#143]
A proposal for the redesign of the facet sections:

<img width="1411" alt="4dn-facets" src="https://cloud.githubusercontent.com/assets/1216518/17781447/5c73e1c8-653d-11e6-84b4-3830ed715a8b.png">

[4DN-facets.pdf](https://github.com/hms-dbmi/fourfront/files/425374/4DN-facets.pdf)

**Comment by ngehlenborg** [comment]
Meant to add that the icons are from the Gizmo symbol set: https://symbolset.com/icons/gizmo

**Comment by carlvitzthum** [comment]
@ngehlenborg on Monday we should discuss how sub-facets might fit into this. Specifically, those are facets that will only appear/expand once the corresponding parent facet has been selected. For example, selecting "immortalized cell line" should produce a sub-facet listing the specific cell lines.

**Comment by carlvitzthum** [comment]
Facets are redesigned, excepting any changes that Burak will want to make when I show him tomorrow,
