### ISSUE TITLE
Odd behavior of permissions on experiments

### ISSUE THREAD

**Issue by aschroed** [hms-dbmi/fourfront#146]
On branch 'permissions_check' I've done the following:

- created a couple new dummy awards - one (Test-4DN) with the viewing group = '4DN', the other (Test-NOT-4DN) without.
- created a couple new dummy labs - one for each award, test-4dn-lab and test-not-4dn-lab.
- made the wrangler user part of the test-4dn-lab as well as a  submits_for the same lab. 
- made the submitter user part of the test-not-4dn-lab and submits_for same
- made an experiment_hic insert with accession "4DNEX067APV1" that has:
status = 'in review'
 test-4dn-lab as its lab
Test-4DN as its award
the wrangler user as it's submitter

I modified base.py to have in class Item a STATUS_ACL = 'in review': ALLOW_LAB_SUBMITTER_EDIT

My expectation would be when logged in as the wrangler user I should be able to both view and edit the experiment_hic item that was submitted by that user.  While the submitter user who did not have viewing group privileges and did not submit the item would not be able to see it.

My expectation was not met  I can only view and edit the experiment when logged in as admin.
The experiment is not viewable by the wrangler user.

I verified the experiment had the expected status (in review).  

I believe that all the status of all the linked Items is 'ALLOW_CURRENT' which should allow everyone to view.

**Comment by j1z0** [comment]
@aschroed - OK the issue is you need to add `{'viewing_groups' :['4DN']}` to the wrangler user.  But do note, in general wranglers are added to the admin group.
