### ISSUE TITLE
Award and Lab for Biosources and Individual

### ISSUE THREAD

**Issue by KorayKirli** [hms-dbmi/fourfront#147]
We want to have the lab and biosources to be common items for 4DN. The schemas had award and lab required, so I now changed it to be not required. The submitted by still will be recorded. 
Is this fine in terms of permissions?
If it is okay, shall we take lab and award out of the schema completely?

**Comment by aschroed** [comment]
Once Jeremy gets to have a look at the issue I had with permissions I will be able to give a better answer but I've also been thinking about this.  

I think for biosources (and maybe individual) the only drawbacks to taking them out of the schema entirely is that 1) only the submitter or someone with admin privileges would be able to edit the biosource while it was being reviewed.  That would likely not be that much of an issue but you could imagine a case where someone submitted a biosource (maybe maliciously) then left the lab and then one of us would need to take care of it. 2) It would not be possible as it is currently set up to make a biosource only visible to 4DN members or lab members - I think if I am correct on how permissions work then as soon a biosource was created then it would be visible to everyone (though I also think that we can probably control that by using a non-default status so it would only be visible to the submitter and admin/wranglers until reviewed?

**Comment by aschroed** [comment]
Going to leave attribution mixin in these now though they are no longer required and closing issue.
