### ISSUE TITLE
Child Parent connection

### ISSUE THREAD

**Issue by KorayKirli** [hms-dbmi/fourfront#77]
Encode used "rev" function to populate the child object with the parent ID. I have some question about that.
1) Is it possible to access the parent object through the child?
2) Is there a requirement of embedding for this to function?
3) Is it possible to iterate it, from child to grand parent?

**Comment by Softworks-Consultancy** [comment]
@KorayKirli Yes, Yes and Yes.  To follow the reverse link you generally want to use the function `paths_filtered_by_status`.  Have a look at tests/testing_views.py in particular the 'testing_link-targets' views, which is tested in the test_post_put_patch.py file.  That goes through a few examples of using rev links.  If you still have questions lets sit down and discuss.
