### ISSUE TITLE
data submission - read in tsv and submit via API

### ISSUE THREAD

**Issue by burakalver** [hms-dbmi/fourfront#87]
Part of step 3 of #75. (But can be implemented before step 2)

Once we have tsv files from #86, read them in and create the objects in the database. Some example code for this is/will be available in the file upload script as the metadata for file gets created. #53

**Comment by j1z0** [comment]
works on excel files, each page being a seperate object.  Can see the scripts here:

https://github.com/hms-dbmi/4DNWranglerTools/tree/master/4DNScripts
